// Real product names for every sample image on the site, keyed by asset filename.
// Written from the actual photographs so that product tiles and image alt text
// carry product information instead of sequence numbers.
// Adding new images: add the file to the relevant array in site-data.js and a
// matching entry here. Any file without an entry falls back to the category label.

export const productNames = {
  // Pet
  "pet-01.jpg": "Plush Bird Cat Toy Set",
  "pet-02.jpg": "Carpeted Cat Tree with Condo and Hammock",
  "pet-03.jpg": "Wooden Cat Tree with Cube Condos",
  "pet-04.jpg": "Compact Wooden Cat Tower with Round Perches",
  "pet-05.jpg": "Carpeted Cat Tree with Ladder and Hammock",
  "pet-06.jpg": "Multi-Level Wooden Cat Tree with Basket",
  "pet-07.jpg": "Curved Designer Cat Tree with Round Condo",
  "pet-08.jpg": "Wooden Cat Tree with Sisal Barrel Condo",
  "pet-09.jpg": "Three-Level Cat Tree with Cushioned Perches",
  "pet-10.jpg": "Wooden Cat Tree with Top Perch and Hammock",
  "pet-11.jpg": "Wooden Cat Tree with Condo and Round Bed",
  "pet-12.jpg": "Large Multi-Condo Cat Tree with Ladder",
  "pet-13.jpg": "Rimmed Plush Pet Bed with Contrast Trim",
  "pet-14.jpg": "Printed Polyester Dog Leash and Collar Set",
  "pet-15.jpg": "Retractable Dog Leash with Brake Button",
  "pet-16.jpg": "Ergonomic Retractable Dog Leash",
  "pet-17.jpg": "Printed Nylon Dog Leash Range",
  "pet-18.jpg": "Dog Boots with Rubber Sole",
  "pet-19.jpg": "Knitted Dog Sweater with Stripe Detail",
  "pet-20.jpg": "Pet Jumpsuit and Denim Jacket Set",
  "pet-21.jpg": "Soft-Sided Pet Carrier with Mesh Windows",
  "pet-22.jpg": "Camouflage Pet Backpack Carrier",
  "pet-23.jpg": "Hard-Sided Pet Travel Crate",
  "pet-24.jpg": "Feather Wand Cat Toy Assortment",
  "pet-25.jpg": "Plush Bear Dog Toy",
  "pet-26.jpg": "Orange Plush Squeaky Dog Toy",
  "pet-27.jpg": "Plush Frog Dog Toy with Rope Handle",
  "pet-28.jpg": "Plush Owl Dog Toy with Wings",
  "pet-29.jpg": "Plush Mouse Cat Toy with Rope Loop",
  "pet-30.jpg": "Red Plush Squeaky Dog Toy",
  "pet-31.jpg": "Plush Rabbit Dog Toy",
  "pet-32.jpg": "Plush Owl Dog Toy with Party Hat",
  "pet-33.jpg": "Plush Hedgehog Dog Toy",
  "pet-34.jpg": "Spiky Plush Dog Toy",

  // Sunglasses & ski goggles
  "sunglasses-01.jpg": "Cylindrical Ski Goggle with Red Mirror Lens",
  "sunglasses-02.jpg": "Frameless Ski Goggles with Carry Case",
  "sunglasses-03.jpg": "Flat-Top Square Sunglasses",
  "sunglasses-04.jpg": "Rimless Square Sunglasses with Gradient Lens",
  "sunglasses-05.jpg": "Round Metal Sunglasses with Pink Gradient Lens",
  "sunglasses-06.jpg": "Shield Sport Sunglasses",
  "sunglasses-07.jpg": "Tortoiseshell Square Sunglasses",
  "sunglasses-08.jpg": "Semi-Rimless Round Sunglasses",
  "sunglasses-09.jpg": "Classic Aviator Sunglasses with Green Lens",
  "sunglasses-10.jpg": "Polarized Rectangular Sunglasses",
  "sunglasses-11.jpg": "Fashion Sunglasses Range with Assorted Lens Colours",
  "sunglasses-12.jpg": "Retro Cat-Eye Sunglasses",
  "sunglasses-13.jpg": "Oversized Mirrored Sunglasses with Retail Display",
  "sunglasses-14.jpg": "Retro Square Sunglasses with Orange Lens",
  "sunglasses-15.jpg": "Assorted Sunglasses in Counter Display Box",

  // Toy
  "toy-10.jpg": "Plush Character Keyring Assortment",
  "toy-01.jpg": "Plush Alien Toy with Suction Cup",
  "toy-02.jpg": "Plush Pony Toy",
  "toy-03.jpg": "Plush Teddy Bear Keyring",
  "toy-04.jpg": "Plush Teddy Bear with Heart",
  "toy-05.jpg": "Plush Dog Keyring with Strap",
  "toy-06.jpg": "Plush Teddy Bear with Checked Bow",
  "toy-07.jpg": "Plush Crocodile Toy",
  "toy-08.jpg": "Plush Dinosaur Keyring",
  "toy-09.jpg": "Plush Character Keyring with Cape",
  "toy-11.jpg": "Plush Penguin Toy with Hat",
  "toy-12.jpg": "Plush Frog Toy",
  "toy-13.jpg": "Plush Penguin with Scarf",
  "toy-14.jpg": "Plush Gorilla Toy",
  "toy-15.jpg": "Plush Penguin Keyring",

  // Home textile
  "hometextile-01.jpg": "Soft Velvet Throw Blanket",
  "hometextile-02.jpg": "Shell-Shaped Decorative Cushions",
  "hometextile-03.jpg": "Dinosaur Shaped Plush Cushion",
  "hometextile-04.jpg": "Flower Shaped Plush Cushion",
  "hometextile-05.jpg": "Pink Flower Plush Cushion",
  "hometextile-06.jpg": "Embroidered Starfish Cushion",
  "hometextile-07.jpg": "Striped Duvet Cover Set",
  "hometextile-08.jpg": "Yarn-Dyed Striped Bedding Set",
  "hometextile-09.jpg": "Textured Weave Cushion",
  "hometextile-10.jpg": "Coastal Print Cushion",
  "hometextile-11.jpg": "Leaf Shaped Baby Quilt",
  "hometextile-12.jpg": "Rainbow Shaped Plush Cushion",
  "hometextile-13.jpg": "Elephant Print Round Baby Mat",
  "hometextile-14.jpg": "Animal Print Baby Blanket Set",
  "hometextile-15.jpg": "Dinosaur Print Baby Blanket Set",
  "hometextile-16.jpg": "Floral Print Baby Comforter",
  "hometextile-17.jpg": "Printed Baby Comforter",
  "hometextile-18.jpg": "Fringed Woven Throw Blanket Range",
  "hometextile-19.jpg": "Quilted Foldable Floor Mattress",

  // Sporting goods
  "sporting-01.jpg": "Metallic Finish Soccer Ball",
  "sporting-02.jpg": "Graphic Print Soccer Ball",
  "sporting-03.jpg": "Graphic Print Basketball",
  "sporting-04.jpg": "Patterned Basketball",
  "sporting-05.jpg": "Competition Volleyball",
  "sporting-06.jpg": "Printed Volleyball",
  "sporting-07.jpg": "Printed American Football",
  "sporting-08.jpg": "Classic American Football",
  "sporting-09.jpg": "Mini Soccer Ball with Floral Print",
  "sporting-10.jpg": "Mini Tennis Ball",
  "sporting-11.jpg": "Animal Print Play Ball",
  "sporting-12.jpg": "Rainbow Striped Kids Play Ball",

  // Shoes
  "shoes-01.jpg": "Kids Character Plush Slippers",
  "shoes-02.jpg": "Kids Character Slippers with Bow Detail",
  "shoes-03.jpg": "Blue Character Plush Slippers",
  "shoes-04.jpg": "Kids Character Slippers with Red Bow",
  "shoes-05.jpg": "Polka-Dot Character Kids Slippers",
  "shoes-06.jpg": "Novelty Character Slipper for Kids",
  "shoes-07.jpg": "Plush Character Slippers for Kids",
  "shoes-08.jpg": "Blue Plush Character Slipper",
  "shoes-09.jpg": "Colourful Kids Trainers with Graphic Sole",
  "shoes-10.jpg": "Pink Character Slippers for Kids",
  "shoes-11.jpg": "Navy Character Plush Slippers",
  "shoes-12.jpg": "Navy Character Slippers with Embroidery",
  "shoes-13.jpg": "Blue Character Slippers with Red Lining",
  "shoes-14.jpg": "Red Character Slippers for Kids",
  "shoes-15.jpg": "Grey Character Slippers for Adults",
  "shoes-16.jpg": "Grey Fleece Slip-On Slippers",
  "shoes-17.jpg": "Pink Character Print Slippers",
  "shoes-18.jpg": "Kids Rubber Rain Boots with Print",
  "shoes-19.jpg": "Embroidered Floral Sneakers",
  "shoes-20.jpg": "White Lace Sneakers with Floral Print",
  "shoes-21.jpg": "Graffiti Print Canvas Sneakers",
  "shoes-22.jpg": "Kids Graffiti Print Rain Boots",

  // Paper items
  "paper-01.jpg": "Character Print Spiral Notebooks",
  "paper-02.jpg": "Mini Notebook and Memo Pad Sets",
  "paper-03.jpg": "Printed Gift Box and Card Sets",
  "paper-04.jpg": "Paper Gift Bags with Die-Cut Handles",
  "paper-05.jpg": "Printed Gift Wrap Sheets",
  "paper-06.jpg": "Character Stationery Gift Set",
  "paper-07.jpg": "Character Sticker Sheet Assortment",

  // Umbrella
  "umbrella-01.jpg": "Kids Clear Dome Umbrella with Character Print",
  "umbrella-02.jpg": "Clear Dome Umbrella with City Print",
  "umbrella-03.jpg": "Kids Transparent Umbrella with Yellow Print",
  "umbrella-04.jpg": "Clear Umbrella with Heart Print",
  "umbrella-05.jpg": "Clear Umbrella with Butterfly Print",
  "umbrella-06.jpg": "Kids Umbrella with Racing Car Print",
  "umbrella-07.jpg": "Kids Clear Umbrella with Character Print",
  "umbrella-08.jpg": "Kids Clear Umbrella with Red Trim",
  "umbrella-09.jpg": "Clear Kids Umbrella with Pink Print",
  "umbrella-10.jpg": "Animal Print Umbrella",
  "umbrella-11.jpg": "Kids Two-Tone Print Umbrella",
  "umbrella-12.jpg": "Pink Kids Umbrella with Balloon Print",
  "umbrella-13.jpg": "Clear Umbrella with Red Butterfly Print",
  "umbrella-14.jpg": "Pink Kids Umbrella with Character Print",
  "umbrella-15.jpg": "Yellow Kids Umbrella with Bee Print",

  // Home decoration
  "home-decor.jpg": "Velvet Upholstered Two-Seat Sofa"
};
